add Cassandra kind
aiven/aiven-operator pull request #225
Opened 2023-01-16 12:51 UTC by byashimov

Adds Cassandra Kind

2023-01-16 12:54 UTC, byashimov commented on controllers/cassandra_controller.go
> +}
@ivan-savciuc `Spec` is unique per Kind, so only `Status` and `ObjectMeta` are sharable. So it doesn't help much, most of the methods has to be customised.

2023-01-16 12:54 UTC, byashimov commented on controllers/generic_service_handler.go
> +	return nil, nil
@ivan-savciuc this change changes a lot actually.

2023-01-16 14:17 UTC, Serpentiel approved these changes
lgtm, good stuff

2023-01-16 15:23 UTC, byashimov commented
> lgtm, good stuff

Sorry, I forgot to update the Changelog :(

2023-01-16 15:34 UTC, Serpentiel approved these changes
lgtm

2023-01-17 08:53 UTC, ivan-savciuc requested changes
Just one tiny thing and we are good to go!

2023-01-17 08:53 UTC, ivan-savciuc commented on main.go
> +	utilruntime.Must(v1alpha1.AddToScheme(scheme))
Please remove this duplicate line

2023-01-17 09:00 UTC, ivan-savciuc approved these changes
LGTM

2023-01-17 09:00 UTC, merged