Add Redis resource to docs
aiven/aiven-operator pull request #227
Opened 2023-01-17 14:49 UTC by staceysalamon-aiven

Add documentation for working with Redis.

2023-01-19 11:48 UTC, byashimov requested changes

2023-01-19 11:48 UTC, byashimov commented on docs/content/en/docs/resources/redis/_index.md
> +  # outputs the Redis connection on the `redis-connection` Secret
```suggestion
  # outputs the Redis connection on the `redis-secret` Secret
```

2023-01-19 11:48 UTC, byashimov commented on docs/content/en/docs/resources/redis/_index.md
> +  plan: startup-2
```suggestion
  plan: startup-4
```

2023-01-19 11:48 UTC, byashimov commented on docs/content/en/docs/resources/redis/_index.md
> +redis-sample   <your-project>   google-europe-west1   startup-2   RUNNING
```suggestion
redis-sample   <your-project>   google-europe-west1   startup-4   RUNNING
```

2023-01-19 14:52 UTC, byashimov commented
LGTM, tested.

2023-01-19 14:52 UTC, byashimov approved these changes

2023-01-19 14:52 UTC, byashimov commented on docs/content/en/docs/resources/redis/_index.md
> +...
Replaced get command with describe

2023-01-23 07:25 UTC, ivan-savciuc approved these changes
LGTM

2023-01-23 07:25 UTC, merged