exclude running acc tests for docs, samples and marked no test
aiven/aiven-operator pull request #230
Opened 2023-01-19 15:08 UTC by byashimov

Don't run acc tests for docs, samples and marked "no test"

2023-01-19 18:07 UTC, ivan-savciuc requested changes
LGTM, we just need to add a new empty line I guess

2023-01-19 18:07 UTC, ivan-savciuc commented on .github/workflows/acceptance-tests-ignore.yaml
> +      - run: 'echo "No build required"'
Please end all files with an empty line

2023-01-19 18:14 UTC, byashimov commented on .github/workflows/acceptance-tests-ignore.yaml
> +      - run: 'echo "No build required"'
Done

2023-01-20 09:10 UTC, ivan-savciuc approved these changes
LGTM

2023-01-20 09:19 UTC, merged