release: v0.8.0
aiven/aiven-operator pull request #268
Opened 2023-02-14 17:09 UTC by byashimov

## About this change—what it does

Release v0.8.0

2023-02-14 19:03 UTC, staceysalamon-aiven requested changes
Just a few minor suggestions for the changelog.

2023-02-14 19:03 UTC, staceysalamon-aiven commented on docs/docs/changelog.md
> +- Add user config fields validations (enum, minimum, maximum, minLength, etc)
```suggestion
- Add user config field validations (enum, minimum, maximum, minLength, and others)
```

2023-02-14 19:03 UTC, staceysalamon-aiven commented on docs/docs/changelog.md
> +- Add `serviceIntegrations` on service types. Only `read_replica` type for now
```suggestion
- Add `serviceIntegrations` on service types. Only the `read_replica` type is available. 
```

2023-02-15 08:52 UTC, Serpentiel approved these changes
lgtm

2023-02-15 09:14 UTC, Serpentiel approved these changes

2023-02-15 09:37 UTC, staceysalamon-aiven approved these changes
Changelog looks good.

2023-02-15 09:41 UTC, merged