feat: add rbac options to helm chart
aiven/aiven-operator pull request #332
Opened 2023-04-04 15:08 UTC by ryaneorth

This change allows the Helm chart be installed without including the creation of cluster-wide resources (ClusterRoles/ClusterRoleBindings). Specifically, this change supports at least 2 use cases:

1. The scenario where the engineer installing the chart has limited (i.e. namespace only) access and cannot install cluster-wide resources. This change allows the cluster-wide resources to be installed separately by cluster administrators while still allowing the engineers to manage the operator itself without having full cluster-wide access.

2. The scenario where the operator only needs to manage resources in a specific namespace and not the entire cluster.

I believe this is the first pull request into this repository since moving the Aiven charts from its [dedicated repository](https://github.com/aiven/aiven-charts) so if a separate PR needs to be made there, let me know and I'd be happy to open one.

2023-04-05 08:49 UTC, byashimov commented
Hi @ryaneorth !
Thanks for the contribution! May I ask you to add a line to the changelog, please?
Regarding moving the charts to this rep, it is still in progress. I need to do few things first that may take a week or two. Then we can release this charts.
Is this urgent for you (the new chart)? Just to know if I need to prioritise this. Thanks.

2023-04-05 10:14 UTC, byashimov requested changes
Please update the changelog.

2023-04-05 15:17 UTC, ryaneorth commented
Hi @byashimov - I've added a line item to the change log. This isn't incredibly urgent, but if we could have a new version of the chart released with these changes in the next week or so that would be very helpful!

2023-04-06 06:09 UTC, byashimov approved these changes

2023-04-06 06:14 UTC, merged