ci(tests): add sweeper to destroy resources after test runs
aiven/aiven-operator pull request #658
Opened 2024-02-28 14:40 UTC by jeff-held-aiven

Adds `sweep` target to Makefile, which will run a sweeper to delete resources in a project. This would include:

- services that have "test-" as a prefix for their name
- service integration endpoints
- VPCs

2024-02-28 16:04 UTC, Serpentiel submitted a review, later dismissed
Please change the commit's prefix to `ci(tests)`.

2024-02-29 09:02 UTC, byashimov requested changes

2024-02-29 09:02 UTC, byashimov commented on sweeper/service_integrations.go
> +}
Can be replaced by `avngen.OmitNotFound`, see below comment.

2024-02-29 11:29 UTC, Serpentiel approved these changes
lgtm, @byashimov @jeff-held-aiven I delegate merging to you folks

2024-02-29 12:02 UTC, byashimov approved these changes
lgtm

2024-02-29 12:02 UTC, merged