feat(clickhousegrant): add new kind
aiven/aiven-operator pull request #752
Opened 2024-06-14 15:13 UTC by rriski

Add new `ClickhouseGrant` kind to control user and role grants.

2024-06-14 15:13 UTC, rriski commented
[tests](https://github.com/aiven/aiven-operator/actions/runs/9518388781)

2024-06-17 12:59 UTC, byashimov requested changes

2024-06-17 15:40 UTC, rriski commented on controllers/clickhousegrant_controller.go
> +			"Instance was created or update on Aiven side, status remains unknown"))
We have the same status condition in many resources (e.g. kafkaacl, connectionpool etc). Should all of these be updated?

![image](https://github.com/aiven/aiven-operator/assets/25483483/a5abb585-6e4d-49a0-a699-17d74bbc6c0c)

2024-06-17 16:34 UTC, rriski commented on controllers/clickhousegrant_controller.go
> +	allRolesQuery         = "SELECT name FROM system.roles"
Using const results in error.

![image](https://github.com/aiven/aiven-operator/assets/25483483/a256e55f-d478-4be8-b74f-2ad8f63062b3)

I feel like this isn't as readable as having them all as `var`'s:

```
var (
	// 'aiven', 'aiven_monitoring', and 'avnadmin' are Aiven-managed users.
	internalAivenRoles = []string{"aiven", "aiven_monitoring", "avnadmin"}
	// "OR user_name IS NULL" is needed to include roles in the result
	allNonAivenUsersQuery = fmt.Sprintf("SELECT name FROM system.users WHERE name NOT IN('%s')", strings.Join(internalAivenRoles, "', '"))
)
const (
	allRolesQuery         = "SELECT name FROM system.roles"
)
```

2024-06-18 08:11 UTC, byashimov commented on controllers/clickhousegrant_controller.go
> +			"Instance was created or update on Aiven side, status remains unknown"))
I mean, mysql creates the secret in `get()` that's why it says `status remains unknown`, but this resource knows its status.

2024-06-18 11:20 UTC, rriski commented on controllers/clickhousegrant_controller.go
> +			"Instance was created or update on Aiven side, status remains unknown"))
Ah now I understood. So you are suggesting to run a query to check if all the privileges have been created on Aiven's side in get. I agree with that approach, I'll add it

2024-06-21 12:09 UTC, byashimov submitted a review, later dismissed
lgtm

2024-06-24 09:47 UTC, byashimov approved these changes

2024-06-24 09:47 UTC, merged