feat: new kind AlloyDB Omni
aiven/aiven-operator pull request #845
Opened 2024-11-15 14:02 UTC by rriski

Adds new kind for AlloyDB Omni (https://aiven.io/alloydb-omni)

2025-01-27 12:31 UTC, rriski commented
[tests](https://github.com/aiven/aiven-operator/actions/runs/12989033631)

2025-02-03 11:17 UTC, byashimov requested changes

2025-02-03 11:17 UTC, byashimov commented on controllers/alloydbomni_controller.go
> +	if newKeyID := credsMap["private_key_id"].(string); newKeyID != currentCreds.PrivateKeyId {
So if `ServiceAccountCredentials` is an empty string, this might panic.

```go
type creds struct {
    PrivateKeyID string `json:"private_key_id"`
}

c := new(creds)
err := json.Unmarshal([]byte(a.Spec.ServiceAccountCredentials), c)

if c.PrivateKeyId != currentCreds.PrivateKeyId {
    ...
}
```

2025-02-03 11:17 UTC, byashimov commented on controllers/serviceuser_controller.go
> +		if c.Component == s.ServiceType || (s.ServiceType == "alloydbomni" && c.Component == "pg") {
nice catch, but also 🤦

2025-02-03 11:24 UTC, rriski commented on api/v1alpha1/alloydbomni_types.go
> +// AlloyDBOmniSpec defines the desired state of AlloyDB Omni instance
This is how Google spells it: https://cloud.google.com/alloydb/omni/docs

2025-02-03 14:13 UTC, rriski commented on controllers/alloydbomni_controller.go
> +}
Yea later commit changes this

2025-02-03 14:13 UTC, rriski commented on utils/alloydbomni/service_account_credentials_validator.go
> +	if !ok {
Resolved by changing to string

2025-02-03 14:15 UTC, rriski commented on controllers/alloydbomni_controller.go
> +	if newKeyID := credsMap["private_key_id"].(string); newKeyID != currentCreds.PrivateKeyId {
Resolved in latest changeset

2025-02-03 14:22 UTC, byashimov approved these changes

2025-02-03 14:23 UTC, merged